import { useState } from "react";

import jsPDF from "jspdf";

function CyberQuiz() {

  const user =
    JSON.parse(
      localStorage.getItem("user")
    );

  const questions = [

    {
      question:
        "What should you never share online?",
      options: [
        "OTP",
        "Password",
        "Bank PIN",
        "All of these",
      ],
      answer:
        "All of these",
    },

    {
      question:
        "Phishing attacks usually happen through?",
      options: [
        "Emails",
        "SMS",
        "Fake Websites",
        "All of these",
      ],
      answer:
        "All of these",
    },

    {
      question:
        "Strong password should contain?",
      options: [
        "Only numbers",
        "Only letters",
        "Letters, numbers & symbols",
        "Date of birth",
      ],
      answer:
        "Letters, numbers & symbols",
    },

    {
      question:
        "What is safest for login security?",
      options: [
        "OTP",
        "2FA",
        "Simple password",
        "Same password everywhere",
      ],
      answer:
        "2FA",
    },

    {
      question:
        "Suspicious links should be?",
      options: [
        "Opened",
        "Ignored",
        "Shared",
        "Downloaded",
      ],
      answer:
        "Ignored",
    },

  ];

  const [currentQuestion,
    setCurrentQuestion] =
    useState(0);

  const [score,
    setScore] =
    useState(0);

  const [showResult,
    setShowResult] =
    useState(false);

  const handleAnswer =
    (option) => {

      if (
        option ===
        questions[
          currentQuestion
        ].answer
      ) {

        setScore(
          score + 1
        );

      }

      const nextQuestion =
        currentQuestion + 1;

      if (
        nextQuestion <
        questions.length
      ) {

        setCurrentQuestion(
          nextQuestion
        );

      } else {

        setShowResult(true);

      }

    };

  // CERTIFICATE PDF

  const downloadCertificate =
    () => {

      const doc =
        new jsPDF();

      // BORDER

      doc.setDrawColor(
        0,
        100,
        0
      );

      doc.setLineWidth(3);

      doc.rect(
        10,
        10,
        190,
        277
      );

      // HEADER

      doc.setFontSize(30);

      doc.setTextColor(
        0,
        100,
        0
      );

      doc.text(
        "CYBERSHIELD AI",
        45,
        40
      );

      // TITLE

      doc.setFontSize(24);

      doc.text(
        "Cyber Awareness Certificate",
        30,
        70
      );

      // USER NAME

      doc.setFontSize(18);

      doc.setTextColor(
        0,
        0,
        0
      );

      doc.text(
        `This certificate is awarded to`,
        50,
        100
      );

      doc.setFontSize(26);

      doc.setTextColor(
        0,
        100,
        0
      );

      doc.text(
        user?.name ||
          "User",
        65,
        125
      );

      // DESCRIPTION

      doc.setFontSize(16);

      doc.setTextColor(
        0,
        0,
        0
      );

      doc.text(
        `For successfully completing the Cyber Security Awareness Quiz`,
        20,
        150
      );

      doc.text(
        `with score ${score}/${questions.length}`,
        60,
        170
      );

      // DATE

      doc.setFontSize(14);

      doc.text(
        `Date: ${new Date().toLocaleDateString()}`,
        20,
        230
      );

      // SIGNATURE

      doc.setFontSize(18);

      doc.text(
        "Authorized By",
        140,
        230
      );

      doc.line(
        135,
        240,
        190,
        240
      );

      // FOOTER

      doc.setFontSize(10);

      doc.setTextColor(
        120,
        120,
        120
      );

      doc.text(
        "Generated by CyberShield AI Cyber Security Platform",
        40,
        270
      );

      // SAVE

      doc.save(
        "Cyber_Awareness_Certificate.pdf"
      );

    };

  return (

    <div className="min-h-screen bg-black text-white flex items-center justify-center p-6">

      <div className="max-w-3xl w-full bg-white/5 border border-green-500/30 rounded-3xl p-10">

        <h1 className="text-5xl font-bold text-green-400 text-center mb-10">

          Cyber Awareness Quiz

        </h1>

        {showResult ? (

          <div className="text-center">

            <h2 className="text-4xl text-green-400 font-bold mb-6">

              Quiz Completed

            </h2>

            <p className="text-2xl mb-8">

              Your Score:

              {" "}

              {score}/
              {questions.length}

            </p>

            <button
              onClick={
                downloadCertificate
              }
              className="bg-green-500 text-black px-8 py-4 rounded-2xl font-bold hover:bg-green-400"
            >

              Download Certificate

            </button>

          </div>

        ) : (

          <div>

            <h2 className="text-3xl mb-10">

              {

                questions[
                  currentQuestion
                ].question

              }

            </h2>

            <div className="space-y-5">

              {

                questions[
                  currentQuestion
                ].options.map(
                  (
                    option,
                    index
                  ) => (

                    <button
                      key={index}
                      onClick={() =>
                        handleAnswer(
                          option
                        )
                      }
                      className="w-full bg-black border border-green-500 p-5 rounded-2xl hover:bg-green-500 hover:text-black transition duration-300"
                    >

                      {option}

                    </button>

                  )
                )

              }

            </div>

          </div>

        )}

      </div>

    </div>

  );

}

export default CyberQuiz;