import { useEffect, useState } from "react";

import axios from "axios";

import jsPDF from "jspdf";

function UserDashboard() {

  const [complaints, setComplaints] =
    useState([]);

  const user =
    JSON.parse(
      localStorage.getItem("user")
    );

 useEffect(() => {
  fetchComplaints();

// eslint-disable-next-line
}, []);
  const fetchComplaints = async () => {

    try {

      const res = await axios.get(

        "https://cybernova-api.onrender.com/api/complaints"

      );

      const userComplaints =
        res.data.filter(

          (item) =>
            item.email === user.email

        );

      setComplaints(userComplaints);

    } catch (error) {

      console.log(error);

    }

  };

  // GOVERNMENT STYLE FIR PDF

  const downloadPDF = (complaint) => {

    const doc = new jsPDF();

    // HEADER

    doc.setFillColor(0, 100, 0);

    doc.rect(0, 0, 210, 30, "F");

    doc.setTextColor(255, 255, 255);

    doc.setFontSize(24);

    doc.text(
      "CYBERSHIELD AI",
      20,
      18
    );

    doc.setFontSize(12);

    doc.text(
      "Government Cyber Crime Investigation Portal",
      20,
      25
    );

    // RESET COLOR

    doc.setTextColor(0, 0, 0);

    // TITLE

    doc.setFontSize(20);

    doc.text(
      "Cyber Crime FIR Report",
      60,
      45
    );

    // LINE

    doc.line(20, 50, 190, 50);

    // FIR DETAILS

    doc.setFontSize(13);

    let y = 65;

    const addField = (
      label,
      value
    ) => {

      doc.setFont(
        "helvetica",
        "bold"
      );

      doc.text(
        `${label}:`,
        20,
        y
      );

      doc.setFont(
        "helvetica",
        "normal"
      );

      doc.text(
        `${value || "N/A"}`,
        80,
        y
      );

      y += 12;

    };

    addField(
      "Complaint ID",
      complaint.complaintId
    );

    addField(
      "Victim Name",
      complaint.name
    );

    addField(
      "Email Address",
      complaint.email
    );

    addField(
      "Phone Number",
      complaint.phone
    );

    addField(
      "Complaint Category",
      complaint.category
    );

    addField(
      "Current Status",
      complaint.status
    );

    addField(
      "Registration Date",
      new Date(
        complaint.createdAt
      ).toLocaleString()
    );

    // DESCRIPTION

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.text(
      "Incident Description:",
      20,
      y + 10
    );

    doc.setFont(
      "helvetica",
      "normal"
    );

    const splitDescription =
      doc.splitTextToSize(

        complaint.description ||
          "No Description",

        160

      );

    doc.text(
      splitDescription,
      20,
      y + 22
    );

    // AI SUMMARY

    y += 60;

    doc.setFillColor(
      240,
      240,
      240
    );

    doc.rect(
      15,
      y,
      180,
      40,
      "F"
    );

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.text(
      "AI Investigation Summary",
      20,
      y + 10
    );

    doc.setFont(
      "helvetica",
      "normal"
    );

    const aiSummary =

      `This cyber complaint appears related to ${complaint.category}. Further digital forensic investigation and cyber evidence analysis are recommended.`;

    const splitAI =
      doc.splitTextToSize(
        aiSummary,
        165
      );

    doc.text(
      splitAI,
      20,
      y + 22
    );

    // FOOTER

    doc.setFontSize(10);

    doc.setTextColor(
      120,
      120,
      120
    );

    doc.text(
      "Generated by CyberShield AI | Digital Cyber Crime Management System",
      20,
      285
    );

    // WATERMARK

    doc.setFontSize(40);

    doc.setTextColor(
      230,
      230,
      230
    );

    doc.text(
      "CYBERSHIELD AI",
      25,
      180,
      {
        angle: 45,
      }
    );

    // SAVE PDF

    doc.save(
      `${complaint.complaintId}-FIR.pdf`
    );

  };

  return (

    <div className="min-h-screen bg-black text-white p-6">

      <h1 className="text-5xl font-bold text-green-400 mb-10">

        User Dashboard

      </h1>

      {/* STATS */}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">

        <div className="bg-blue-950 border border-green-500 rounded-2xl p-6">

          <h2 className="text-2xl">
            Total Complaints
          </h2>

          <p className="text-5xl text-green-400 font-bold mt-4">

            {complaints.length}

          </p>

        </div>

        <div className="bg-blue-950 border border-yellow-500 rounded-2xl p-6">

          <h2 className="text-2xl">
            Pending
          </h2>

          <p className="text-5xl text-yellow-400 font-bold mt-4">

            {

              complaints.filter(
                (c) =>
                  c.status === "Pending"
              ).length

            }

          </p>

        </div>

        <div className="bg-blue-950 border border-blue-500 rounded-2xl p-6">

          <h2 className="text-2xl">
            Resolved
          </h2>

          <p className="text-5xl text-blue-400 font-bold mt-4">

            {

              complaints.filter(
                (c) =>
                  c.status === "Resolved"
              ).length

            }

          </p>

        </div>

      </div>

      {/* TABLE */}

      <div className="overflow-x-auto">

        <table className="w-full border border-green-500">

          <thead>

            <tr className="bg-green-600 text-black">

              <th className="p-4">
                Complaint No.
              </th>

              <th className="p-4">
                Complaint Type
              </th>

              <th className="p-4">
                Status
              </th>

              <th className="p-4">
                Date
              </th>

              <th className="p-4">
                FIR PDF
              </th>

            </tr>

          </thead>

          <tbody>

            {

              complaints.map((item) => (

                <tr
                  key={item._id}
                  className="text-center border-b border-green-500"
                >

                  <td className="p-4">

                    {item.complaintId}

                  </td>

                  <td className="p-4">

                    {item.category}

                  </td>

                  <td className="p-4">

                    {item.status}

                  </td>

                  <td className="p-4">

                    {

                      new Date(
                        item.createdAt
                      ).toLocaleDateString()

                    }

                  </td>

                  <td className="p-4">

                    <button
                      onClick={() =>
                        downloadPDF(item)
                      }
                      className="bg-green-500 text-black px-4 py-2 rounded-lg font-bold hover:bg-green-400"
                    >

                      Download FIR

                    </button>

                  </td>

                </tr>

              ))

            }

          </tbody>

        </table>

      </div>

    </div>

  );

}

export default UserDashboard;